import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { ToastContainer } from "react-toastify";
// import { Geist, Geist_Mono } from "next/font/google";

//Figma design dev mail 
// https://www.figma.com/design/DVpattukvvK1GTsizzzvOD/AK-Full-E-Commerce-Website-UI-UX-Design?node-id=1-3&p=f&t=MA45h3DIny92ALSA-0

const poppins = localFont({
  src: "../public/fonts/poppins-regular.ttf",
  variable: "--font-poppins-regular",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${poppins.className}`}
      >
        {children}
         <ToastContainer />
      </body>
    </html>
  );
}
